### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [orialmog/Cake.ProjHelpers#1]
i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#152

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by orialmog** [comment]
Hi gep

I've updated the source repo with a few comments but did not update the version number, so i manually pushed to nuget with replace=true. Let me know what else i am suppose to do ( do i need to update the xml file in the web site? )

**Comment by gep13** [comment]
@orialmog yes. If you could submit a new PR to the website repo, adding in a section for your addin, then the site will pull in the documentation that you have just added in.  Thanks!

**Comment by gep13** [comment]
@orialmog just wanted to touch base to see if you had thought about doing this. Thanks!

**Comment by orialmog** [comment]
Hi gep, I did look into this but left it after i guessed the xml doc file should be included in the nuget package for the website to parse, just got busy with other things, will take a look tonight though.

**Comment by gep13** [comment]
Yes, that is correct. Xml file needs to be in the nuget package.

Let me know if you have any follow up questions.

**Comment by orialmog** [comment]
hey gep,
sorted and pull request was sent, sorry for the stale commit.

**Comment by gep13** [comment]
Thanks for getting this sorted out. Will try to look at the PR soon.
